1801042630: 1801042630.o HexVector.o HexAdapter.o Array.o
	g++ 1801042630.o HexVector.o HexAdapter.o Array.o -o 1801042630
1801042630.o: 1801042630.cpp
	g++ -c -std=gnu++11 1801042630.cpp
Array.o: Array.cpp
	g++ -c -std=gnu++11 Array.cpp	
HexAdapter.o: HexAdapter.cpp
	g++ -c -std=gnu++11 HexAdapter.cpp
HexVector.o: HexVector.cpp
	g++ -c -std=gnu++11 HexVector.cpp